### PR TITLE
Improve GitHub Actions workflows

### PR DESCRIPTION
**Pull request by cgytrus**
## Description
almost completely rewrites the current GH Actions workflows
here's what they (will) do:
- doesn't run a billion random workflows on each PR/push
  - only build non-bundled non-single-file on pr
  - only build bundled on push
- only publish x64 versions in the bleeding edge release
- publish a umtlib nuget package on gh release (TODO)
- cleaner code (although this could also get some improvements)

### Caveats
_might_ be slower than the current ones

### Notes
squash on merge please, the commit names are atrocious lmao

### CODE REVIEW

**Comment by Miepee** [comment]
Can you put the Csproj changes into a seperate PR please?

**Comment by Grossley** [comment]
What is the status of this pull request?

**Comment by Miepee** [comment]
Still draft and needs some discussion.

**Comment by Miepee** [comment]
This PR has a lot of conflicts, has some stuff already addressed, and also is pretty unreviewable and unmaintainable.
I do want to have the actions files cleaned up at one point, but this is not the way to do it.

**Pull request closed without merging**
